#! /bin/bash

# Load environment variables from .env file
set -a
source ../.env
set +a
unset _JAVA_OPTIONS

dir=$(pwd)
# resultsDir="$dir/results"
# mkdir -p "$resultsDir"

echo "Creating view for tracking planning and execution statistics"
PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -p $DB_PORT -d $DB -U $DB_USER -c "CREATE EXTENSION IF NOT EXISTS pg_stat_statements;"

echo "Restarting postgres"
docker restart postgres-thesis

# Run Scala file with spark-submit
./spark-3.5.0/bin/spark-submit \
    --class processing.Processing \
    --master "local[$CORELIMIT]" \
    --driver-memory "${MEMLIMIT}g" \
    --jars "$dir/postgresql-42.6.0.jar" \
    --driver-java-options "-Dlogger_file_name=$dir/log4j_collection.log" \
    "$dir/app.jar"
