#! /bin/bash

# Load environment variables from .env file
set -a
source .env
set +a

dir=$(pwd)
# resultsDir="$dir/results"
# mkdir -p "$resultsDir"

# Run Scala file with spark-submit
./spark-3.4.0/bin/spark-submit \
    --class PostgresDataProcessing.PostgresDataProcessing \
    --master "local[$CORELIMIT]" \
    --driver-memory "${MEMLIMIT}g" \
    --jars "$dir/postgresql-42.6.0.jar" \
    --driver-java-options "-Dlogger_file_name=$dir/log4j_collection.log" \
    "$dir/app.jar"
