#! /bin/bash

set -a
source .env
set +a

dir=$(pwd)
# resultsDir="$dir/results"
# mkdir -p "$resultsDir"

./spark-3.3.1/bin/spark-submit \
    --class PostgresDataProcessing.PostgresDataProcessing \
    --master "local[$CORELIMIT]" \
    --driver-memory "${MEMLIMIT}g" \
    --jars "$dir/app.jar" \
    --driver-java-options "-Dlogger_file_name=$dir/log4j_collection.log" \
    "$dir/app.jar" \
