version: '3.8'
services:
  postgres:
    image: postgres-thesis
    container_name: postgres-thesis
    build:
      context: ./app
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_DB: thesis
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  app-build:
    image: thesis-processing
    container_name: build-script
    build:
      context: ./app
      dockerfile: Dockerfile.spark
    volumes:
      - ./app:/home/app
    working_dir: /home/app
    entrypoint: []
    command:
      - bash
      - -c
      - |
          sbt assembly
          mv target/scala-2.13/app.jar app.jar
  cli-build:
    image: cli-ui
    container_name: cli-ui
    build:
      context: ./cli
      dockerfile: Dockerfile.cli
    volumes:
      - ./cli:/home/app
      - ./bin:/home/bin
    working_dir: /home/app
    entrypoint: []
    command:
      - bash
      - -c
      - |
          go build -o ui ui.go
          mv ui ../bin