FROM golang:1.20 AS dev

# RUN apk add git
ENV GO111MODULE=off
RUN go get github.com/rivo/tview
RUN go get github.com/joho/godotenv
# RUN go get github.com/tj/go-spin
# RUN go get github.com/gdamore/tcell